#pragma once

#define IDI_CHIRAMI             1

#define IDS_APP_TITLE           100
#define IDS_STATUS_LOADING      101
#define IDS_ERR_FILE_OPEN       102
#define IDS_ERR_DECODE          103
#define IDS_ERR_IMAGE_TOO_LARGE 104
#define IDS_ABOUT_TITLE         105
#define IDS_ABOUT_TEXT          106
#define IDS_FILTER_IMAGES       107
#define IDS_FILTER_ALL          108
#define IDS_ERR_SAVE            109
#define IDS_CLIPBOARD_NAME      110
#define IDS_FILTER_PNG          111
#define IDS_FILTER_JPEG         112
#define IDS_FILTER_BMP          113
#define IDS_FILTER_TIFF         114
#define IDS_ERR_NO_IMAGES       115
#define IDS_ERR_RESIZE          116
#define IDS_ABOUT_TJ_LOADED     117
#define IDS_ABOUT_TJ_MISSING    118
#define IDS_ABOUT_FORMATS       119
#define IDS_ASSOC_TYPENAME      120
#define IDS_ASSOC_DESCRIPTION   121
#define IDS_ASSOC_REGISTERED    122
#define IDS_ASSOC_UNREGISTERED  123
#define IDS_ASSOC_MOVED         124
#define IDS_ERR_ASSOC           125
#define IDS_META_TITLE          126
#define IDS_META_COL_NAME       127
#define IDS_META_COL_VALUE      128
#define IDS_META_GROUP_FILE     129
#define IDS_META_GROUP_IMAGE    130
#define IDS_META_GROUP_PNGTEXT  131
#define IDS_META_GROUP_WIC      132
#define IDS_META_FILENAME       133
#define IDS_META_FOLDER         134
#define IDS_META_FILESIZE       135
#define IDS_META_SIZE_FMT       136
#define IDS_META_MODIFIED       137
#define IDS_META_CREATED        138
#define IDS_META_FORMAT         139
#define IDS_META_DIMENSIONS     140
#define IDS_META_PIXELFORMAT    141
#define IDS_META_DPI            142
#define IDS_META_FRAMES         143
#define IDS_META_COMPRESSED     144
#define IDS_META_COPY_VALUE     145
#define IDS_META_COPY_ALL       146
#define IDS_META_ERROR          147
#define IDS_META_DISPLAYFORMAT  148

#define IDR_MAINMENU            200

#define IDD_RESIZE              300
#define IDC_RESIZE_WIDTH        1001
#define IDC_RESIZE_HEIGHT       1002
#define IDC_RESIZE_KEEPASPECT   1003
#define IDC_RESIZE_WIDTH_PCT    1004
#define IDC_RESIZE_HEIGHT_PCT   1005

#define IDM_FILE_OPEN           40001
#define IDM_FILE_EXIT           40002
#define IDM_FILE_SAVEAS         40003
#define IDM_VIEW_FIT            40101
#define IDM_VIEW_ACTUAL         40102
#define IDM_VIEW_ZOOMIN         40103
#define IDM_VIEW_ZOOMOUT        40104
#define IDM_VIEW_FULLSCREEN     40105
#define IDM_VIEW_PROPERTIES     40106
#define IDM_HELP_ABOUT          40201
#define IDM_EDIT_PASTE          40301
#define IDM_EDIT_ROTATE_CW      40302
#define IDM_EDIT_ROTATE_CCW     40303
#define IDM_EDIT_FLIP_H         40304
#define IDM_EDIT_FLIP_V         40305
#define IDM_EDIT_CROP           40306
#define IDM_EDIT_BLACKOUT       40307
#define IDM_EDIT_RESIZE         40308
#define IDM_SORT_NAME           40401
#define IDM_SORT_DATE           40402
#define IDM_SORT_SIZE           40403
#define IDM_SORT_ASC            40404
#define IDM_SORT_DESC           40405
#define IDM_ASSOC_REGISTER      40501
#define IDM_ASSOC_UNREGISTER    40502
#define IDM_ASSOC_SETTINGS      40503
